import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Nav from "@/components/Nav";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Crypto</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main className=" flex items-center  text-center justify-center gradient-text  h-screen w-full px-10">
        <div className=" flex flex-col mx-auto text-white ">
          <div className="font-bold md:text-[6.25rem] mb-8 text-4xl gradient-text">
            <h1 className=" ">Your Crypto.</h1>
            <h1 className=" md:mt-24">Family Style.</h1>
          </div>

          <p className=" md:text-xl text-sm bg-opacity-25 text-center text-[#484848] whitespace-nowrap">
            Explore Ethereum with the best wallet for iOS. <br />
            Interacting with crypto has never been so simple.
          </p>
          <div className=" bg-black placeholder:text-white bg-opacity-20 my-8 border border-[#484848] rounded-[3.25rem] flex items-center justify-between">
            <input
              type="email"
              className=" bg-transparent w-full outline-none p-6"
              placeholder=" Enter your email"
            />
            <button className=" bg-white bg-opacity-0 sheen border text-sm whitespace-nowrap rounded-[1.875rem] px-4 w-[9.5rem] min-h-[3.625rem] mr-2 md:text-lg">
              Join Waitlist
            </button>
          </div>
          <p>
            <span className=" text-[#484848]">Want early access?</span> Learn
            how
          </p>
        </div>
      </main>
    </>
  );
}
